// GENERATED by scripts/extract-constant-notes.mjs. Do not hand-edit.
// Tiles whose "Note" output is identical for every set of inputs -- reference
// prose, not an observation about the answer. app.js moves these out of the
// answer region and into the one collapsed Details block, so a tile page shows
// the number first and keeps its explanation in the single place it belongs.
// The compute still returns the note; only where it is PRINTED changes.
//
// 1280 of 2080 tiles, one bit each in TOOLS order (see the
// generator for why this is a bitmap and not a list of ids).
import { TOOLS } from "./tools-data.js";

const BITS = "BACE3wAAAEIAAHoIQPj8B0CCARIA0Ho8v/4APYCBACBQYYM4kA4AAPCxAAAAAsAAAIL//yaJC/AB/j4HgO95f/D/A3CABwB8/gs/0D8EAHD2AwDgf7j/BcP/j9/ff5z/47/5P+aOf6f7/6+7///9vOz/+///1/////f//3/f//3///8////mP/z/v/9fD57JfPcx/OYbAAD+4//TzvH///9v/7//w9/x7eu+//m/we///7f//z5drf82338FAH48AODyQxjsIkD8yZpx8pPz/78H+/+HAgjz9/+vPI//1PN9Y/v/7v3///9v/w/+fz7mu9m/HOne//9f+//abt/fn/v+2/8=";

const bytes = Uint8Array.from(atob(BITS), (c) => c.charCodeAt(0));
export const CONSTANT_NOTE_TILES = new Set(
  TOOLS.filter((t, i) => (bytes[i >> 3] >> (i & 7)) & 1).map((t) => t.id)
);
