// GENERATED by scripts/extract-constant-notes.mjs. Do not hand-edit.
// Tiles whose "Note" output is identical for every set of inputs -- reference
// prose, not an observation about the answer. app.js moves these out of the
// answer region and into the one collapsed Details block, so a tile page shows
// the number first and keeps its explanation in the single place it belongs.
// The compute still returns the note; only where it is PRINTED changes.
//
// 1332 of 2144 tiles, one bit each in TOOLS order (see the
// generator for why this is a bitmap and not a list of ids).
import { TOOLS } from "./tools-data.js";

const BITS = "BACE3wAAAEL/AQDQQwDC5/8HgAQDJACg9Xh+/QF6AL8VCAACFTaIA+kAAAAfCwAAQAAYAP5B8P/fksQF+AB/v88B4HveH/z/ABzgAQCf/8IP9A8BAJz9AAD4H+5/wfD/4/f3H+f/+G/+j7nj3+n+/+vu/38/L/v//v//9f////3//9/3f//////P/7/5D///7//Xg2cy330Mv/kGAID/+P+0c/z////b/+//8Hd8+7rvf76/we///7f//z5drf82338FAH48AODyQxjsIkD8yZpx8pPz/78H+/+HAgjz9/+vPI//1PN9Y/v/7v3///9v/w/+fz7mu9m/HOne//9f+//abt/fn/v+2//39w==";

const bytes = Uint8Array.from(atob(BITS), (c) => c.charCodeAt(0));
export const CONSTANT_NOTE_TILES = new Set(
  TOOLS.filter((t, i) => (bytes[i >> 3] >> (i & 7)) & 1).map((t) => t.id)
);
