// GENERATED by scripts/extract-constant-notes.mjs. Do not hand-edit.
// Tiles whose "Note" output is identical for every set of inputs -- reference
// prose, not an observation about the answer. app.js moves these out of the
// answer region and into the one collapsed Details block, so a tile page shows
// the number first and keeps its explanation in the single place it belongs.
// The compute still returns the note; only where it is PRINTED changes.
//
// 1340 of 2157 tiles, one bit each in TOOLS order (see the
// generator for why this is a bitmap and not a list of ids).
import { TOOLS } from "./tools-data.js";

const BITS = "BACE3wAAAEL/AQDQQwDC578PAAkGSABA6/H8+gP0AH4rEAAEKmwQB9IBAAA+FgAAgAAwAPyD4P+/JYmXuwAf4O/3OQB8z/uD/x+AAzwA4PNf+IH+IQCAsx8AAP/D/S8Y/n/8/v7j/B//zf8xd/w73f9/3f3/7+dl/9///7/+//+/////+/7v//////n/N//h///9/3rwTOa7j+E33wAA8B//n3aO////f/v//R/+jm9f9/3P9zf4/f//9v/fp6v13+b7rwDAjwcAXH4Ig10EiD9ZM05+cv7/92D//1AAYf7+/5Xn8Z96vm9s/9+9/////+3/wf/Px3w3+5cj3fv//2v/X9vt+/tz33/7//4e";

const bytes = Uint8Array.from(atob(BITS), (c) => c.charCodeAt(0));
export const CONSTANT_NOTE_TILES = new Set(
  TOOLS.filter((t, i) => (bytes[i >> 3] >> (i & 7)) & 1).map((t) => t.id)
);
