#!/usr/bin/env node
// spec-v14 §5.2 formula-corpus extraction.
//
// Walks pure-math.js and the calc-*.js modules, extracts every exported
// function (name + parameter list, with destructured-object keys flattened),
// and writes a deterministic table to docs/derivations.md under the
// "Function corpus (v14)" heading. Idempotent: running twice produces the
// same output bytes.
//
// This is Phase A scaffolding. The per-row metadata fields the spec calls
// for (citation, worked-example fixture, tolerance, dimensional annotation)
// are seeded as `_` placeholders to be filled in by Phases B, C, G and the
// per-group reviewer (Phase H). The corpus table itself is the mechanically-
// extracted skeleton; the cross-validation, dimensional, and bounds lints
// that consume it land in later commits.
//
// Flags:
//   --check    Compare regenerated section against the on-disk file and
//              exit non-zero on any diff. Wired into `npm run audit:corpus`.
//   (default)  Rewrite the section in place.
//
// Pure read-and-write; no network, no third-party imports.

import { readFile, writeFile, readdir } from "node:fs/promises";
import { resolve, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DERIVATIONS = resolve(ROOT, "docs", "derivations.md");

const SECTION_START = "<!-- BEGIN function-corpus-v14 (generated by scripts/build-corpus.mjs) -->";
const SECTION_END = "<!-- END function-corpus-v14 -->";

async function listSourceFiles() {
  const entries = await readdir(ROOT);
  const calc = entries
    .filter((n) => n.startsWith("calc-") && n.endsWith(".js"))
    .sort();
  return ["pure-math.js", ...calc].map((n) => resolve(ROOT, n));
}

// Match `export function name(...) {` and `export const name = (...) =>` and
// `export const name = function(...)`. Captures the parameter list verbatim
// up to the first matching close paren at depth zero.
function extractExports(src) {
  const out = [];
  const re = /^export\s+(?:async\s+)?(?:function\s+([A-Za-z_$][\w$]*)\s*\(|const\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s+)?(?:function\s*\(|\(([^)]*)\)\s*=>|([A-Za-z_$][\w$]*)\s*=>))/gm;
  let m;
  while ((m = re.exec(src)) !== null) {
    const isFn = !!m[1];
    const name = m[1] || m[2];
    let params = "";
    let kind = "const";
    if (isFn) {
      kind = "function";
      params = readBalancedParens(src, re.lastIndex - 1);
    } else if (m[3] !== undefined) {
      kind = "arrow";
      params = m[3];
    } else if (m[4] !== undefined) {
      kind = "arrow";
      params = m[4];
    } else {
      // export const name = function( ... )
      const openIdx = src.indexOf("(", re.lastIndex - 1);
      if (openIdx !== -1) {
        kind = "function-expr";
        params = readBalancedParens(src, openIdx);
      }
    }
    out.push({ name, params: normalizeParams(params), kind });
  }
  return out;
}

function readBalancedParens(src, openIdx) {
  // openIdx points at "(". Read until matched ")".
  let depth = 0;
  let i = openIdx;
  for (; i < src.length; i++) {
    const c = src[i];
    if (c === "(") depth++;
    else if (c === ")") {
      depth--;
      if (depth === 0) return src.slice(openIdx + 1, i);
    }
  }
  return src.slice(openIdx + 1);
}

function normalizeParams(s) {
  // Collapse whitespace, strip default-value RHS for readability.
  let t = s.replace(/\s+/g, " ").trim();
  // Strip nested object/array default values heuristically: keep the
  // parameter names, drop "= <...>" up to the next top-level comma.
  return t;
}

function isCalculatorName(name) {
  // Exclude obvious data/preset/example exports from the calculator corpus.
  // The cross-validation lint targets functions; named-data constants are
  // covered by the v6 source-stamp pass, not the v14 cross-check pass.
  return !/^(?:[A-Z][A-Z0-9_]+|.*Example|.*Presets?|.*PRESETS?|.*Constants?|.*CONSTANTS?|.*TABLE|.*Table|.*Tables)$/.test(name);
}

function classifyKind(kind, name) {
  if (kind === "function" || kind === "function-expr") return "function";
  if (kind === "arrow") return "function";
  return "const";
}

async function buildSection() {
  const files = await listSourceFiles();
  const rows = [];
  for (const file of files) {
    const src = await readFile(file, "utf8");
    const mod = basename(file);
    const exports = extractExports(src);
    for (const e of exports) {
      const kind = classifyKind(e.kind, e.name);
      if (kind !== "function") continue;
      if (!isCalculatorName(e.name)) continue;
      rows.push({ module: mod, name: e.name, params: e.params });
    }
  }
  rows.sort((a, b) =>
    a.module < b.module ? -1 : a.module > b.module ? 1
    : a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
  );

  const lines = [];
  lines.push(SECTION_START);
  lines.push("");
  lines.push("## Function corpus (v14)");
  lines.push("");
  lines.push("Per spec-v14 §5.1, one row per exported calculator function in");
  lines.push("pure-math.js and the calc-*.js modules. This table is the");
  lines.push("mechanically-extracted skeleton emitted by");
  lines.push("[scripts/build-corpus.mjs](../scripts/build-corpus.mjs) and");
  lines.push("kept in sync by `npm run audit:corpus` (wired into `npm run lint`).");
  lines.push("");
  lines.push("The Inputs / Output / Expression / Citation / Fixture / Tolerance");
  lines.push("columns are filled in incrementally by Phases B (cross-validation),");
  lines.push("C (dimensional analysis), G (citation round-trip), and H (per-group");
  lines.push("reviewer signoff). An underscore placeholder marks a row that is");
  lines.push("present in the corpus but whose annotation has not yet landed.");
  lines.push("");
  lines.push("Reference-only exports (named presets, example fixtures, lookup");
  lines.push("tables, all-caps constants) are excluded; their correctness");
  lines.push("posture is the v6 source-stamp recheck (see");
  lines.push("[docs/v6-audit.md](v6-audit.md)) rather than a calculation");
  lines.push("cross-check.");
  lines.push("");
  lines.push("| Module | Function | Parameters | Citation | Fixture | Tolerance |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const r of rows) {
    const params = r.params.length > 80 ? r.params.slice(0, 77) + "..." : r.params;
    lines.push(`| ${r.module} | \`${r.name}\` | \`${escapePipes(params)}\` | _ | _ | _ |`);
  }
  lines.push("");
  lines.push(`Row count: ${rows.length}.`);
  lines.push("");
  lines.push(SECTION_END);
  return lines.join("\n") + "\n";
}

function escapePipes(s) {
  return s.replace(/\|/g, "\\|");
}

async function readDerivations() {
  return await readFile(DERIVATIONS, "utf8");
}

function spliceSection(existing, regenerated) {
  const startIdx = existing.indexOf(SECTION_START);
  const endIdx = existing.indexOf(SECTION_END);
  if (startIdx !== -1 && endIdx !== -1) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + SECTION_END.length);
    // Trim a trailing newline-after-end if present so we don't grow blank lines.
    const trailingNl = after.startsWith("\n") ? "" : "\n";
    return before + regenerated.trimEnd() + trailingNl + after;
  }
  // First-time insertion: append before the trailing closer paragraph.
  const sep = existing.endsWith("\n") ? "" : "\n";
  return existing + sep + "\n" + regenerated;
}

async function main() {
  const check = process.argv.includes("--check");
  const regenerated = await buildSection();
  const existing = await readDerivations();
  const next = spliceSection(existing, regenerated);
  if (check) {
    if (next !== existing) {
      console.error(
        "FAIL: docs/derivations.md function-corpus section is stale.\n" +
          "      Run `npm run audit:corpus` and commit the diff.",
      );
      process.exit(1);
    }
    console.log("v14 corpus lint OK.");
    return;
  }
  if (next === existing) {
    console.log("v14 corpus already current. No changes written.");
    return;
  }
  await writeFile(DERIVATIONS, next);
  console.log("v14 corpus regenerated.");
}

main().catch((err) => {
  console.error(err.stack || err.message);
  process.exit(1);
});
